title: "Mehrdad Ahmadinejad"
description: "Ph.D. Researcher | Mechanical Engineering | University of Vermont"
theme: null  # Disabling default Jekyll theme
markdown: kramdown
permalink: pretty  # Enables clean URLs (removes .html)
